config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'web/welcome#index'

  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'logout', to: 'auth#logout', as: :auth_logout
    get 'auth/failure', to: 'auth#failure'

    resources :repositories, only: %i[index new create show] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/shared/_footer.html.slim
footer.fixed-bottom.py-1.p-0.bg-dark.text-light
    .container.row
        .col.d-flex.align-items-center
            p.mb-0.me-3
                = t('footer.github')
            p.mb-0.mr-auto
                - if I18n.locale == :ru
                    = link_to t('languages.en'), url_for(locale: 'en')
                - else
                    = link_to t('languages.ru'), url_for(locale: 'ru')

app/views/layouts/shared/_nav.html.slim
.container-fluid.p-1.me-2.mb-2.bg-dark
  .navbar.navbar-expand-md.bg-dark
    .container
      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav
          li.nav-item.me-2
            = link_to t('links.home'), root_path, class: 'nav-link text-light'
        ul.nav.nav-pills.navbar-nav.mr-auto.align-items-center.justify-content-between
          - if current_user
            li.nav-item.me-2
                = link_to t('links.repositories'), repositories_path, class: 'btn btn-outline-light'
            li.nav-item.me-2
                = link_to t('links.add'), new_repository_path, class: 'btn btn-outline-light'
            li.nav.item.me-2.link-light
                    = current_user.email
            li.nav-item.me-2
              = button_to t('links.logout'), auth_logout_path, data: { turbo: false }, method: :delete, class: 'btn btn-outline-light'
          - else
            li.nav-item.me-2
              = button_to t('links.login'), auth_request_path(:github), data: { turbo: false }, method: :post, class: 'btn btn-outline-light'