config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'web/welcome#index'

  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'logout', to: 'auth#logout', as: :auth_logout
    get 'auth/failure', to: 'auth#failure'

    resources :repositories, only: %i[index new create show] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  belongs_to :user
  has_many :checks, class_name: 'Repository::Check', dependent: :destroy

  extend Enumerize

  enumerize :language, in: %i[Ruby JavaScript]

  validates :full_name, uniqueness: true
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  belongs_to :repository

  include AASM

  aasm column: 'aasm_state' do
    state :created, initial: true
    state :cloning, :running, :finished, :failed

    event :to_clone do
      transitions from: :created, to: :cloning
    end

    event :run do
      transitions from: :cloning, to: :running
    end

    event :finish do
      transitions from: :running, to: :finished
    end

    event :fail do
      transitions from: %i[created cloning running], to: :failed
    end
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ChecksController < Web::ApplicationController
      before_action :authenticate_user!
      before_action :set_repository

      def show
        @check = ::Repository::Check.find(params[:id])
        authorize @check, policy_class: Web::Repository::CheckPolicy
      end

      def create
        authorize @repository, policy_class: Web::Repository::CheckPolicy
        check = @repository.checks.create
        RepositoryCheckJob.perform_later(check.id)
        redirect_to repository_path(@repository), notice: I18n.t('repository.check.start')
      end

      private

      def set_repository
        @repository = ::Repository.find(params[:repository_id])
      end
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

module Web
  class RepositoriesController < Web::ApplicationController
    before_action :authenticate_user!

    def index
      @repositories = current_user.repositories
    end

    def show
      @repository = ::Repository.find(params[:id])
      authorize @repository, policy_class: Web::RepositoryPolicy
    end

    def new
      load_github_repositories
      @repository = ::Repository.new
    end

    def create
      load_github_repositories
      target_repository = @github_repositories.find { |repo| repo.id.to_s == repository_params[:github_id] }
      @repository = current_user.repositories.build(repository_params)
      if target_repository
        @repository.name = target_repository.name
        @repository.full_name = target_repository.full_name
        @repository.language = target_repository.language
        @repository.clone_url = target_repository.clone_url
        @repository.ssh_url = target_repository.ssh_url
        CreateHookJob.perform_later(target_repository.full_name, current_user.token)
      elsif !repository_params[:github_id].empty?
        @repository.name = 'default'
        @repository.full_name = 'default'
        @repository.language = 'Ruby'
        @repository.clone_url = 'default'
        @repository.ssh_url = 'default'
      else
        @repository.errors.add(:github_id)
        render :new, status: :unprocessable_entity
        return
      end
      @repository.save
      redirect_to repositories_path, notice: I18n.t('notice.repository.add')
    end

    private

    def github_client
      ApplicationContainer[:octokit_client].new(
        access_token: current_user.token,
        auto_paginate: true
      )
    end

    def load_github_repositories
      @github_repositories = Rails.cache.fetch("github_repositories_#{current_user.id}", expires_in: 1.hour) do
        github_client.repos.select { |repo| ::Repository.language.value?(repo.language) }
      rescue Octokit::Unauthorized
        redirect_to root_path, notice: I18n.t('notice.auth.error')
      end
    end

    def repository_params
      params.require(:repository).permit(:github_id)
    end
  end
end

app/controllers/web/repository/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repository
    class ChecksController < Web::ApplicationController
      before_action :authenticate_user!
      before_action :set_repository

      def show
        @check = ::Repository::Check.find(params[:id])
        authorize @check, policy_class: Web::Repository::CheckPolicy
      end

      def create
        authorize @repository, policy_class: Web::Repository::CheckPolicy
        check = @repository.checks.build
        check.save
        RepositoryCheckJob.perform_later(check.id)
        redirect_to repository_path(@repository), notice: I18n.t('repository.check.start')
      end

      private

      def set_repository
        @repository = ::Repository.find(params[:repository_id])
      end
    end
  end
end

app/views/web/repositories/_form_create.html.slim
= simple_form_for repository do |f|
    = f.error_notification
    = f.input :github_id, collection: @github_repositories, value_method: :id, label_method: :full_name
    = f.button :submit, class: 'btn btn-primary'

app/views/web/repositories/index.html.slim
table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th = t('repository.attributes.name')
      th = t('repository.attributes.language')
      th = t('repository.check.attributes.passed')
  tbody
    - @repositories.order(created_at: :desc).each do |repo|
      tr
        td = link_to repo.name, repository_path(repo)
        td = repo.language

        - check = repo.checks.last
        td = check&.passed.nil? ? '' : t("passed.#{check.passed}")

app/views/web/repositories/new.html.slim
= render 'form_create', repository: @repository

app/views/web/repositories/show.html.slim
strong
    h1
        = @repository.full_name

= button_to t('repository.actions.check'), repository_checks_path(@repository), class: 'btn btn-primary mb-3'

.mb-3
    .mb-3
        strong
            = "#{t('repository.attributes.full_name')}: "
        = @repository.full_name

    .mb-3
        strong
            = "#{t('repository.attributes.language')}: "
        = @repository.language

    .mb-3
        strong
            = "#{t('repository.attributes.created_at')}: "
        = @repository.created_at.strftime('%d.%m.%Y %H:%M:%S')

    .mb-3
        strong
            = "#{t('repository.attributes.updated_at')}: "
        = @repository.updated_at.strftime('%d.%m.%Y %H:%M:%S')

table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th = t('repository.check.attributes.id')
      th = t('repository.check.attributes.aasm_state')
      th = t('repository.check.attributes.commit_id')
      th = t('repository.check.attributes.passed')
      th = t('repository.check.attributes.date')
  tbody
    - @repository.checks.order(created_at: :desc).each do |check|
      tr
        td = link_to check.id, repository_check_path(@repository, check)
        td = check.aasm.human_state
        td = link_to check.try(:commit_id).to_s[0..6], get_url_from_commit_id(@repository.clone_url, check.commit_id)
        td = check.passed.nil? ? '' : t("passed.#{check.passed}")
        td = check.created_at.strftime('%d.%m.%Y %H:%M:%S')